version: '3.0'
services: 
  read_own:
    image: reader
    container_name: reader
    restart: always
    ports:
      - 4395:8080
    volumes:
      - ./logs:/logs
      - ./storage:/storage
    environment:
      - SPRING_PROFILES_ACTIVE=prod
