version: '3'
services:
  app:
    image: 'npm:latest'
    restatrt: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'mariadb-aria:latest'
    restatrt: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '<a strong passowrd>'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: '<username from config.json>'
      MYSQL_PASSWORD: '<strong password from config.json>'
    volumes:
      - ./data/mysql:/var/lib/mysql
